name: Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    runs-on: ubuntu-latest
    steps:
    
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with: 
          app_id: 239964
          # installation_id not needed IF the app is installed on this current repo
#           installation_id: 30074716
          private_key: ${{ secrets.APP_SECRET_KEY }}
    
      - uses: actions/checkout@v3
      
      - name: terraform init
        run: terraform init
        working-directory: "."
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
      
